apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-node-18
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-node-18
  template:
    metadata:
      labels:
        app: app-node-18
    spec:
      containers:
      - name: app-node-18
        image: jennyffernm/app-node-18:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-configmap
        resources:
            requests:
              cpu: 400m
