apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: public-access
rules:
- apiGroups: [""]
  resources:
  - pods
  - services
  - configmaps
  - secrets
  - persistentvolumeclaims
  - endpoints
  verbs: ["get", "list", "watch"]
